/*==========================================INFOTRIS MASTER SEARCH DATABASE==========================================RULES1. Every searchable item goes here.2. Search.js NEVER needs editing.3. Only add new objects.Types:coursecareer*/const INFOTRIS_INDEX = [    // =========================    // COURSES    // =========================    {        id: "python",        type: "course",        title: "Python",        description:            "Complete Python programming course.",        keywords: [            "python",            "programming",            "backend",            "automation",            "coding",            "beginner"        ],        url: "courses/python/"    },    {        id: "dsa",        type: "course",        title: "Data Structures & Algorithms",        description:            "Master data structures and algorithms.",        keywords: [            "dsa",            "algorithm",            "algorithms",            "data structures",            "tree",            "graph",            "linked list"        ],        url: "courses/dsa/"    },    {        id: "problem-solving",        type: "course",        title: "Problem Solving",        description:            "Learn to break down problems, write pseudocode, debug, and practice coding patterns.",        keywords: [            "problem solving",            "debugging",            "pseudocode",            "patterns",            "coding"        ],        url: "courses/problem-solving/"    },        {
        id: "html",
        type: "course",
        title: "HTML",
        description: "Structure the web with semantic, accessible markup — the skeleton of every site.",
        keywords: ["html", "markup", "semantic", "web", "structure", "beginner", "accessibility"],
        url: "courses/html/"
    },
    // =========================
    // CAREERS    // =========================    {        id: "python-developer",        type: "career",        title: "Python Developer",        description:            "Become a Python Developer.",        keywords: [            "python",            "developer",            "backend",            "career"        ],        url: "careers/python-developer/"    }    ];console.log("Infotris Database Loaded");